services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: mercedes-benz-mssql
    hostname: mssql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "MercedesBenz2026!"
      MSSQL_PID: "Developer"
    volumes:
      - mssql-data:/var/opt/mssql
      - ./data/database:/database
      - ./scripts/sql:/scripts
    networks:
      - mercedes-network
    restart: unless-stopped

volumes:
  mssql-data:
    driver: local

networks:
  mercedes-network:
    driver: bridge
